// NOTE: This file is automatically generated by test_converter.py using itl tests.

#ifdef __CUDACC__
#pragma nv_diagnostic push
#pragma nv_diag_suppress 1046
#endif

#include "tests_additional.cu"
#include "generated/tests_libieeep1788_class.cu"
#include "generated/tests_pow_rev.cu"
#include "generated/tests_libieeep1788_mul_rev.cu"
#include "generated/tests_ieee1788_constructors.cu"
#include "generated/tests_abs_rev.cu"
#include "generated/tests_c_xsc.cu"
#include "generated/tests_libieeep1788_rev.cu"
#include "generated/tests_libieeep1788_elem.cu"
#include "generated/tests_libieeep1788_reduction.cu"
#include "generated/tests_libieeep1788_rec_bool.cu"
#include "generated/tests_libieeep1788_cancel.cu"
#include "generated/tests_libieeep1788_bool.cu"
#include "generated/tests_atan2.cu"
#include "generated/tests_mpfi.cu"
#include "generated/tests_intervalarithmeticjl.cu"
#include "generated/tests_libieeep1788_set.cu"
#include "generated/tests_filib.cu"
#include "generated/tests_ieee1788_exceptions.cu"
#include "generated/tests_libieeep1788_num.cu"
#include "generated/tests_libieeep1788_overlap.cu"

#ifdef __CUDACC__
#pragma nv_diagnostic pop
#pragma nv_diag_default 1046
#endif

int main()
{
    tests_additional<double>();
    tests_libieeep1788_class<double>();
    tests_pow_rev<double>();
    tests_libieeep1788_mul_rev<double>();
    tests_ieee1788_constructors<double>();
    tests_abs_rev<double>();
    tests_c_xsc<double>();
    tests_libieeep1788_rev<double>();
    tests_libieeep1788_elem<double>();
    tests_libieeep1788_reduction<double>();
    tests_libieeep1788_rec_bool<double>();
    tests_libieeep1788_cancel<double>();
    tests_libieeep1788_bool<double>();
    tests_atan2<double>();
    tests_mpfi<double>();
    tests_intervalarithmeticjl<double>();
    tests_libieeep1788_set<double>();
    tests_filib<double>();
    tests_ieee1788_exceptions<double>();
    tests_libieeep1788_num<double>();
    tests_libieeep1788_overlap<double>();

    return 0;
}
