name: GPU workflow test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Display the path
      shell: cmd.exe /k "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" {0}
      run: echo %PATH%
    - name: gpu info
      run: nvidia-smi
    - name: directory info
      run: ls
    - name: nvidia compiler info
      run: nvcc --version
