name: GPU workflow test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Display the path
      shell: C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe -noe -c "&{Import-Module """C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"""; Enter-VsDevShell 84598446}"
      run: echo ${env:PATH}
    - name: gpu info
      run: nvidia-smi
    - name: directory info
      run: ls
    - name: nvidia compiler info
      run: nvcc --version
